### ISSUE TITLE
initial setup

### ISSUE THREAD

**Issue by somedevreally** [powerivq/ttrss-pusher#2] opened 2020-04-20 15:51 UTC
Readme > how to use> is clear but filename is case-sensitive 
class is "Pusher" in init.php
so plugin folder name should also be "Pusher" and
`It is a system plugin, therefore you need to turn it on in the config.php file. The plugin's name is pusher` should be "Pusher" too
otherwise tt-rss wont load and will show blank page.

Hope it will help somebody

**Comment by powerivq** [comment] 2020-04-20 17:57
Thank you for looking into that.

I am not seeing the same issue here while using the docker container. What is your runtime environment (OS, ttrss version)?

Also notice that the system plugins (e.g. https://git.tt-rss.org/fox/tt-rss/src/master/plugins/af_comics/init.php) are all using the same naming pattern and seems to be working fine?

**Comment by somedevreally** [comment] 2020-04-20 19:30
am on docker too, Tiny Tiny RSS v20.04-11a9d3bd9 
now the plugin is not showing up on plugin tab. after multiple recreating of the container i cannot see it on plugin page :(

EDIT: ok this is strange, if i add it to config.php it do not show on plugin page
`	define('PLUGINS', 'auth_internal, note, nginx_xaccel, Pusher');
`

**Comment by somedevreally** [comment] 2020-04-20 19:39
got this error on system event log

```
E_ERROR (1)	plugins.local/pusher/vendor/web-token/jwt-util-ecc/NistCurve.php:50	

Uncaught Error: Call to undefined function gmp_init() in /var/www/html/tt-rss/plugins.local/pusher/vendor/web-token/jwt-util-ecc/NistCurve.php:50 Stack trace: #0 /var/www/html/tt-rss/plugins.local/pusher/vendor/minishlink/web-push/src/VAPID.php(178): Jose\Component\Core\Util\Ecc\NistCurve::curve256() #1 /var/www/html/tt-rss/plugins.local/pusher/init.php(39): Minishlink\WebPush\VAPID::createVapidKeys() #2 /var/www/html/tt-rss/plugins.local/pusher/init.php(30): Pusher->init_keys() #3 /var/www/html/tt-rss/classes/pluginhost.php(261): Pusher->init(Object(PluginHost)) #4 /var/www/html/tt-rss/include/functions.php(1515): PluginHost->load('auth_internal, ...', 1) #5 /var/www/html/tt-rss/prefs.php(22): init_plugins() #6 {main} thrown

```

**Comment by powerivq** [comment] 2020-04-20 19:44
Have you installed `gmp` as README requirement says?

```
apk add gmp-dev gmp
docker-php-ext-install gmp
```
This is what I use for my alpine container.

**Comment by somedevreally** [comment] 2020-04-20 19:53
```
RUN apk add --no-cache php7 php7-fpm \
	php7-pdo php7-gd php7-pgsql php7-pdo_pgsql php7-mbstring \
	php7-intl php7-xml php7-curl php7-session \
	php7-dom php7-fileinfo php7-json \
	php7-pcntl php7-posix php7-zip \
	php7-curl \
	openssl \
	gmp-dev gmp \
```
this is my alpine dockerfile

**Comment by powerivq** [comment] 2020-04-20 22:39
Have you ran `docker-php-ext-install gmp`?

**Comment by somedevreally** [comment] 2020-04-21 01:22
how do i run that command? when added to dockerfile it give an error
` returned a non-zero code: 1
`

**Comment by powerivq** [comment] 2020-04-21 01:41
Ideally it should work. You can test run it in an active container and see what error it throws. Without the error it is really difficult to tell what went wrong.

**Comment by somedevreally** [comment] 2020-04-21 02:01
in an active container it give error
` docker-php-ext-install: not found
`

**Comment by powerivq** [comment] 2020-04-21 03:32
Your problem for sure is caused by the missing dependency `gmp`. I can't tell what your PHP configuration is. If you built your own PHP container, you need to build it with `--with-gmp` (see https://www.php.net/manual/en/gmp.installation.php). If you use an already-built one, I suggest you ditch that one for an official PHP docker container (https://hub.docker.com/_/php?tab=description) They have both Apache and Nginx version and you can install gmp extensions by running that `docker-php-ext-install` command.

**Comment by powerivq** [comment] 2020-06-29 01:53
Closing this as not active. Feel free to reopen.

**Closed as completed by powerivq** 2020-06-29 01:53 UTC
